version: 2.1

workflows:
  node-tests:
    jobs:
      build:
        docker:
          image: un1que1d/sample_nodejs:0.1
          auth:
            username: un1que1d
            password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
          
