version: 2.1

executors:
  my-executor:
    machine:
      - image: ubuntu-2004:202010-01

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run:
            shell: /bin/sh
            command: docker build -t sample-nodejs-app . 
          
          
